[[repos]]
repo = "local"

[[repos.hooks]]
id = "prettier"
name = "prettier"
entry = "./node_modules/.bin/prettier --write"
language = "system"
types = ["text"]
files = "\\.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$"

[[repos.hooks]]
id = "eslint"
name = "Lint and fix with ESLint"
entry = "./node_modules/.bin/eslint --fix"
language = "system"
types = ["file"]
files = "\\.(js|jsx|ts|tsx|vue)$"

[[repos.hooks]]
id = "fmt"
name = "fmt"
entry = "node ./fmt.js"
language = "system"
types = ["file"]
files = "\\.(js|jsx|ts|tsx)$"

[[repos.hooks]]
id = "build"
name = "build"
entry = "npm run fmt && npm run lint:eslint && npm run type-check && npm run build"
language = "system"
always_run = true
pass_filenames = false
